packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  cpu-features: false
  esbuild: true
  msw: true
  prisma: true
  protobufjs: false
  ssh2: false
  unrs-resolver: true
