import { Release } from '@flesh-and-blood/types';

export const SETS = Release;
export type SetT = `${Release}`;

export type SetGrouping = { group: string; sets: readonly SetT[] };

export const SET_GROUPS: SetGrouping[] = [
  {
    group: 'Main Sets',
    sets: [
      SETS.WelcomeToRathe,
      SETS.ArcaneRising,
      SETS.CrucibleOfWar,
      SETS.Monarch,
      SETS.TalesOfAria,
      SETS.Everfest,
      SETS.Uprising,
      SETS.Dynasty,
      SETS.Outsiders,
      SETS.DuskTillDawn,
      SETS.BrightLights,
      SETS.HeavyHitters,
      SETS.PartTheMistveil,
      SETS.Rosetta,
      SETS.TheHunted,
      SETS.HighSeas,
      SETS.SuperSlam,
      SETS.CompendiumOfRathe,
      SETS.OmensOfTheThirdAge,
    ],
  },
  {
    group: 'Blitz Decks',
    sets: [
      SETS.BoltynBlitzDeck,
      SETS.ChaneBlitzDeck,
      SETS.LeviaBlitzDeck,
      SETS.PrismBlitzDeck,
      SETS.BriarBlitzDeck,
      SETS.LexiBlitzDeck,
      SETS.OldhimBlitzDeck,
      SETS.DromaiBlitzDeck,
      SETS.FaiBlitzDeck,
      SETS.ArakniBlitzDeck,
      SETS.AzaleaBlitzDeck,
      SETS.BenjiBlitzDeck,
      SETS.KatsuBlitzDeck,
      SETS.RiptideBlitzDeck,
      SETS.UzuriBlitzDeck,
      SETS.KassaiBlitzDeck,
      SETS.KayoBlitzDeck,
      SETS.BetsyBlitzDeck,
      SETS.OlympiaBlitzDeck,
      SETS.RhinarBlitzDeck,
      SETS.VictorBlitzDeck,
      SETS.EnigmaBlitzDeck,
      SETS.NuuBlitzDeck,
      SETS.ZenBlitzDeck,
      SETS.FlorianBlitzDeck,
      SETS.VerdanceBlitzDeck,
      SETS.AuroraBlitzDeck,
      SETS.OscilioBlitzDeck,
      SETS.ArakniBlitzDeckARK,
      SETS.ArakniWebOfDeceitBlitzDeck,
      SETS.CindraBlitzDeck,
      SETS.FangBlitzDeck,
    ],
  },
  {
    group: 'Hero Decks',
    sets: [SETS.BravoHeroDeck, SETS.DorintheaHeroDeck, SETS.KatsuHeroDeck, SETS.RhinarHeroDeck],
  },
  {
    group: 'Armory Decks',
    sets: [
      SETS.ArmoryDeckKayo,
      SETS.ArmoryDeckBoltyn,
      SETS.ArmoryDeckAzalea,
      SETS.ArmoryDeckDash,
      SETS.ArmoryDeckOriginsJarl,
      SETS.ArmoryDeckAurora,
      SETS.ArmoryDeckMaxx,
      SETS.ArmoryDeckGravyBones,
      SETS.ArmoryDeckIra,
      SETS.ArmoryDeckLegendsPrism,
      SETS.ArmoryDeckLegendsViserai,
      SETS.ArmoryDeckPleiades,
      SETS.ArmoryDeckRhinar,
      SETS.ArmoryDeckArakni,
      SETS.ArmoryDeckOriginsHala,
      SETS.ArmoryDeckZyggy,
      SETS.ArmoryDeckOlympia,
    ],
  },
  {
    group: 'Silver Age Decks',
    sets: [
      SETS.BravoSilverAgeDeck,
      SETS.DashSilverAgeDeck,
      SETS.IyslanderSilverAgeDeck,
      SETS.KayoSilverAgeDeck,
      SETS.ViseraiSilverAgeDeck,
      SETS.ArakniSilverAgeDeck,
      SETS.AzaleaSilverAgeDeck,
      SETS.DorintheaSilverAgeDeck,
      SETS.EnigmaSilverAgeDeck,
      SETS.FaiSilverAgeDeck,
      SETS.BlazeSilverAgeDeck,
      SETS.BoltynSilverAgeDeck,
      SETS.BriarSilverAgeDeck,
      SETS.GravyBonesSilverAgeDeck,
      SETS.LyathSilverAgeDeck,
    ],
  },
  {
    group: 'Mastery Packs',
    sets: [SETS.MasteryPackGuardian, SETS.MasteryPackWarrior],
  },
  {
    group: 'First Strike',
    sets: [SETS.FirstStrikeAurora, SETS.FirstStrikeTerra],
  },
  {
    group: 'Other',
    sets: [
      SETS.IraWelcomeDeck,
      SETS.HistoryPack1,
      SETS.ClassicBattlesRhinarDorinthea,
      SETS.RoundTheTable,
      SETS.BravoDemoDeck,
      SETS.SmashPalace,
      SETS.DorintheaDemoDeck,
      SETS.IAR,
      SETS.Promos,
      SETS.GEM,
      SETS.TournamentPack,
    ],
  },
];

export const SET_ORDER: SetT[] = [
  SETS.IraWelcomeDeck,
  SETS.WelcomeToRathe,
  SETS.BravoHeroDeck,
  SETS.DorintheaHeroDeck,
  SETS.KatsuHeroDeck,
  SETS.RhinarHeroDeck,
  SETS.ArcaneRising,
  SETS.CrucibleOfWar,
  SETS.Monarch,
  SETS.BoltynBlitzDeck,
  SETS.ChaneBlitzDeck,
  SETS.LeviaBlitzDeck,
  SETS.PrismBlitzDeck,
  SETS.TalesOfAria,
  SETS.BriarBlitzDeck,
  SETS.LexiBlitzDeck,
  SETS.OldhimBlitzDeck,
  SETS.Everfest,
  SETS.HistoryPack1,
  SETS.ClassicBattlesRhinarDorinthea,
  SETS.Uprising,
  SETS.DromaiBlitzDeck,
  SETS.FaiBlitzDeck,
  SETS.Dynasty,
  SETS.Outsiders,
  SETS.ArakniBlitzDeck,
  SETS.AzaleaBlitzDeck,
  SETS.BenjiBlitzDeck,
  SETS.KatsuBlitzDeck,
  SETS.RiptideBlitzDeck,
  SETS.UzuriBlitzDeck,
  SETS.DuskTillDawn,
  SETS.RoundTheTable,
  SETS.BrightLights,
  SETS.HeavyHitters,
  SETS.KassaiBlitzDeck,
  SETS.KayoBlitzDeck,
  SETS.BetsyBlitzDeck,
  SETS.OlympiaBlitzDeck,
  SETS.RhinarBlitzDeck,
  SETS.VictorBlitzDeck,
  SETS.ArmoryDeckKayo,
  SETS.PartTheMistveil,
  SETS.EnigmaBlitzDeck,
  SETS.NuuBlitzDeck,
  SETS.ZenBlitzDeck,
  SETS.ArmoryDeckBoltyn,
  SETS.FirstStrikeAurora,
  SETS.FirstStrikeTerra,
  SETS.ArmoryDeckAzalea,
  SETS.Rosetta,
  SETS.FlorianBlitzDeck,
  SETS.VerdanceBlitzDeck,
  SETS.AuroraBlitzDeck,
  SETS.OscilioBlitzDeck,
  SETS.ArmoryDeckDash,
  SETS.ArmoryDeckOriginsJarl,
  SETS.TheHunted,
  SETS.ArakniBlitzDeckARK,
  SETS.ArakniWebOfDeceitBlitzDeck,
  SETS.CindraBlitzDeck,
  SETS.FangBlitzDeck,
  SETS.ArmoryDeckAurora,
  SETS.ArmoryDeckMaxx,
  SETS.ArmoryDeckGravyBones,
  SETS.HighSeas,
  SETS.ArmoryDeckIra,
  SETS.ArmoryDeckLegendsPrism,
  SETS.ArmoryDeckLegendsViserai,
  SETS.MasteryPackGuardian,
  SETS.BravoDemoDeck,
  SETS.ArmoryDeckPleiades,
  SETS.SuperSlam,
  SETS.SmashPalace,
  SETS.ArmoryDeckRhinar,
  SETS.ArmoryDeckArakni,
  SETS.CompendiumOfRathe,
  SETS.BravoSilverAgeDeck,
  SETS.DashSilverAgeDeck,
  SETS.IyslanderSilverAgeDeck,
  SETS.KayoSilverAgeDeck,
  SETS.ViseraiSilverAgeDeck,
  SETS.ArakniSilverAgeDeck,
  SETS.AzaleaSilverAgeDeck,
  SETS.DorintheaSilverAgeDeck,
  SETS.EnigmaSilverAgeDeck,
  SETS.FaiSilverAgeDeck,
  SETS.ArmoryDeckOriginsHala,
  SETS.ArmoryDeckZyggy,
  SETS.OmensOfTheThirdAge,
  SETS.BlazeSilverAgeDeck,
  SETS.BoltynSilverAgeDeck,
  SETS.BriarSilverAgeDeck,
  SETS.GravyBonesSilverAgeDeck,
  SETS.LyathSilverAgeDeck,
  SETS.ArmoryDeckOlympia,
  SETS.MasteryPackWarrior,
  SETS.DorintheaDemoDeck,
  SETS.IAR,
  SETS.Promos,
  SETS.GEM,
  SETS.TournamentPack,
];
