import { FOILINGS } from '../../shared/game/foiling';
import { RARITIES } from '../../shared/game/rarity';
import { SETS } from '../../shared/game/set';
import type { Printing } from '../domain/card';

// Images from external sources that are not on the Fabrary CDN use full URLs directly from the fab database.
export const CARD_PRINTING_OVERRIDES: Record<string, Printing[]> = {
  'trot-along-blue': [
    {
      identifier: 'ZH_FAB401',
      print: 'FAB401',
      set: SETS.Promos,
      rarity: RARITIES.Promo,
      edition: null,
      foiling: FOILINGS.Regular,
      treatments: ['Extended Art', 'Alternate Art'],
      image:
        'https://legendstory-production-s3-public.s3.amazonaws.com/media/cards/large/ZH_FAB401.webp',
      backPrinting: null,
      artists: ['Carlos Cruchaga'],
    },
  ],
  'scar-for-a-scar-red': [
    {
      identifier: 'JA_FAB443-RF',
      print: 'FAB443',
      set: SETS.Promos,
      rarity: RARITIES.Promo,
      edition: null,
      foiling: FOILINGS.Rainbow,
      treatments: ['Extended Art', 'Alternate Art'],
      image:
        'https://legendstory-production-s3-public.s3.amazonaws.com/media/cards/large/JA_FAB443-RF.webp',
      backPrinting: null,
      artists: ['Kanadekana'],
    },
  ],
  'razor-reflex-red': [
    {
      identifier: 'FAB475',
      print: 'FAB475-Rainbow-Extended Art',
      set: SETS.Promos,
      rarity: RARITIES.Promo,
      edition: null,
      foiling: FOILINGS.Rainbow,
      treatments: ['Extended Art', 'Alternate Art'],
      image: 'https://content.fabrary.net/cards/FAB475-RF.webp',
      backPrinting: null,
      artists: ['Isuardi Therianto'],
    },
  ],
  'comet-collision-yellow': [
    {
      identifier: 'OMN110',
      print: 'OMN110',
      set: SETS.OmensOfTheThirdAge,
      rarity: RARITIES.Common,
      edition: null,
      foiling: FOILINGS.Regular,
      treatments: [],
      image: 'https://content.fabrary.net/cards/OMN110.webp',
      backPrinting: null,
      artists: ['Dzulfikar Aliy'],
    },
    {
      identifier: 'OMN110',
      print: 'OMN110-Rainbow',
      set: SETS.OmensOfTheThirdAge,
      rarity: RARITIES.Common,
      edition: null,
      foiling: FOILINGS.Rainbow,
      treatments: [],
      image: 'https://content.fabrary.net/cards/OMN110-RF.webp',
      backPrinting: null,
      artists: ['Dzulfikar Aliy'],
    },
  ],
  'comet-collision-blue': [
    {
      identifier: 'OMN111',
      print: 'OMN111',
      set: SETS.OmensOfTheThirdAge,
      rarity: RARITIES.Common,
      edition: null,
      foiling: FOILINGS.Regular,
      treatments: [],
      image: 'https://content.fabrary.net/cards/OMN111.webp',
      backPrinting: null,
      artists: ['Dzulfikar Aliy'],
    },
    {
      identifier: 'OMN111',
      print: 'OMN111-Rainbow',
      set: SETS.OmensOfTheThirdAge,
      rarity: RARITIES.Common,
      edition: null,
      foiling: FOILINGS.Rainbow,
      treatments: [],
      image: 'https://content.fabrary.net/cards/OMN111-RF.webp',
      backPrinting: null,
      artists: ['Dzulfikar Aliy'],
    },
  ],
  'comet-collision-red': [
    {
      identifier: 'OMN109',
      print: 'OMN109',
      set: SETS.OmensOfTheThirdAge,
      rarity: RARITIES.Common,
      edition: null,
      foiling: FOILINGS.Regular,
      treatments: [],
      image: 'https://content.fabrary.net/cards/OMN109.webp',
      backPrinting: null,
      artists: ['Dzulfikar Aliy'],
    },
    {
      identifier: 'OMN109',
      print: 'OMN109-Rainbow',
      set: SETS.OmensOfTheThirdAge,
      rarity: RARITIES.Common,
      edition: null,
      foiling: FOILINGS.Rainbow,
      treatments: [],
      image: 'https://content.fabrary.net/cards/OMN109-RF.webp',
      backPrinting: null,
      artists: ['Dzulfikar Aliy'],
    },
  ],
};
